### ISSUE TITLE
Consider replacing config syntax with TOML

### ISSUE THREAD

**Issue by chrismurf** [aphysci/gravity#172]
On a current program, we've been using TOML to configure multiple elements of the system from a single config file.  TOML is nice because it looks a lot like the traditional "INI" file, but has some limited support for arrays, structs, and date/time types.  That makes it a lot easier to represent some complex objects, like TDMA schedules.

We've been using [TOML++](https://marzer.github.io/tomlplusplus/), which has worked out well so far.

Example:
```toml
[database]
host = 'localhost'
port = 12345
name = 'db_name'
poll_period = 00:00:01.000

[node]
address = "192.168.1.1"
name = "Node"

[node.tdma]
lead_time = 00:00:01

[node.tdma.schedule]
length = 00:02:00
slots = [
  {offset = 00:00:00, queues = ["queue_a", "queue_b"]},
  {offset = 00:01:00, queues = ["queue_a"]}
]
```

I think we should consider moving Gravity to it.  It would reduce the number of custom parts of Gravity, and I think it would largely support all the functionality we use today.  The only obviously missing piece is the ability to do math in config files - I'm not sure how widely used that is.
